# Netlify configuration for NextStop Dashboard
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Enable SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
